enum Direction {
    N = 0,
    NE = 1,
    E = 2,
    SE = 3,
    S = 4,
    SW = 5,
    W = 6,
    NW = 7,
}

enum MenuItemId {
    mine = "mine",
    wall = "wall",
    channel = "channel",
    upstair = "upstair",
    downstair = "downstair",
    udstair = "udstair",
    upramp = "upramp",
    stockpile = "stockpile",
    remove = "remove",
    leatherworks = "leatherworks",
    quern = "quern",
    millstone = "millstone",
    loom = "loom",
    clothier = "clothier",
    bowyer = "bowyer",
    carpenter = "carpenter",
    forge = "forge",
    magmaforge = "magmaforge",
    jeweler = "jeweler",
    mason = "mason",
    butcher = "butcher",
    tanner = "tanner",
    craftsdwarf = "craftsdwarf",
    siege = "siege",
    mechanic = "mechanic",
    still = "still",
    farmers = "farmers",
    kitchen = "kitchen",
    fishery = "fishery",
    ashery = "ashery",
    dyer = "dyer",
    soap = "soap",
    screw = "screw",
    bed = "bed",
    chair = "chair",
    door = "door",
    inspect = "inspect",
}

export { Direction, MenuItemId };
